### ISSUE TITLE
Ability to see Processed Rule in Events

### ISSUE THREAD

**Issue by dsibiski** [AutoElevate/roadmap#19]
From feature request:

> "The events tab has a wonderful "Outcome" column. However, I feel that the column is lonely and underutilized. I would like to see or have a link to the processed rule in that column. This would greatly improve the ability for a technician / administrator to troubleshoot approval and elevation issues."

Additional votes: 3

**Comment by sydevinfra** [comment]
Very much needed.
It would also also facilitate rule creation if you can filter events where no rules matched.

**Comment by dsibiski** [comment]
The functionality here is taken care of in: https://github.com/AutoElevate/roadmap/issues/25
